# Generated by Django 4.1.2 on 2022-10-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_futbolistas_delete_futbolista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futbolistas',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
